# Generated by Django 5.0 on 2024-08-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='', upload_to='profile_pics'),
        ),
    ]
